//
// Created by thehe on 8/5/2024.
//

#ifndef LAB_PROBLEM1_COLORFILEFORMATEXCEPTION_H
#define LAB_PROBLEM1_COLORFILEFORMATEXCEPTION_H


class ColorFileFormatException {

};


#endif //LAB_PROBLEM1_COLORFILEFORMATEXCEPTION_H
