//
// Created by thehe on 8/5/2024.
//

#ifndef LAB_PROBLEM1_COLORVECTOROUTOFRANGEEXCEPTION_H
#define LAB_PROBLEM1_COLORVECTOROUTOFRANGEEXCEPTION_H


class ColorVectorOutOfRangeException {

};


#endif //LAB_PROBLEM1_COLORVECTOROUTOFRANGEEXCEPTION_H
