//
// Created by thehe on 8/5/2024.
//

#ifndef LAB_PROBLEM1_COORDINATEOUTOFRANGEEXCEPTION_H
#define LAB_PROBLEM1_COORDINATEOUTOFRANGEEXCEPTION_H


class CoordinateOutOfRangeException {

};


#endif //LAB_PROBLEM1_COORDINATEOUTOFRANGEEXCEPTION_H
